### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "yooo",
  "email": "testing@example.com",
  "password": "Password123!"
}

### Update Username
PATCH http://localhost:3000/api/users/Rizze
Content-Type: application/json

{
    "newUsername": "yooo" 
}

### Update Email
PATCH http://localhost:3000/api/users/testuser
Content-Type: application/json

{
    "email": "newemail@example.com"
}

### Update Password
PATCH http://localhost:3000/api/users/testuser
Content-Type: application/json

{
    "oldPassword": "Password123!",
    "newPassword": "Newpassword456!"
}

### Multiple Updates
PATCH http://localhost:3000/api/users/testuser
Content-Type: application/json

{
    "newUsername": "brandnewname",
    "email": "brand@new.email",
    "oldPassword": "Password123!",
    "newPassword": "Newpassword456!"
}

### Delete user
DELETE http://localhost:3000/api/users/testuser